### ISSUE TITLE
PHP fatal error on config save

### ISSUE THREAD

**Issue by SimWhite** [shaman/opencart-bitcoin#1]
When I try to save setting I get a blank page.

Web server error log shows the following: "PHP Fatal error:  Call to undefined method Loader::library() in /var/www/html/admin/controller/payment/bitcoin.php on line 161, referer: http://127.0.0.1/admin/index.php?route=payment/bitcoin&token=blablabla."

Here is the 160 and 161 lines of /var/www/html/admin/controller/payment/bitcoin.php:
        // Load dependencies
        $this->load->library('bitcoin');

Also I check the presence of /var/www/html/system/library/bitcoin.php file. It exists.

**Comment by shaman** [comment]
Hi, what is your OpenCart core version?

**Comment by SimWhite** [comment]
Version 2.0.3.2_rc taked from OpenCart repo.

**Comment by shaman** [comment]
Looks really mistake, it's tested with many 2.0+ versions by me, /system/library/bitcoin.php is really readable?

**Comment by shaman** [comment]
btw, not sure about alpha repo, try to get latest stable release 2.0.3.1 anyway:
http://www.opencart.com/index.php?route=download/download

**Comment by SimWhite** [comment]
Yeah, it's working with 2.0.3.1. Thanks!
