### ISSUE TITLE
Call to undefined method Loader::library()

### ISSUE THREAD

**Issue by f-r-e-e-s-k-y** [shaman/opencart-bitcoin#3]
I have a setup with CentOS 6 server with official nginx 1.8.0 + php 5.6 + php-fpm from remi for testing. The oc shop works and I can install the extension, however I can not activate it via the backend/gui/Payment List. I get a blank page, in the log I see an Error 500:

nginx log:
"...POST /admin/index.php?route=payment/bitcoin&token=xyz HTTP/1.1" 500..."

php-fpm log:
"PHP Fatal error:  Call to undefined method Loader::library() in /var/www/html/admin/controller/payment/bitcoin.php on line 161

Does this extension work with nginx? Is there a way to manually hit the switch in the db?

**Comment by f-r-e-e-s-k-y** [comment]
opencart version is 2.1.0.1

**Comment by shaman** [comment]
Hi,

seems that module incompatible with latest version OpenCart 2.1.0.1.
BTW, /var/www/html/admin/controller/payment/bitcoin.php is exist and writable?

**Comment by shaman** [comment]
Hi, 
module was upgraded to 2.1.0.1 version
https://github.com/shaman/opencart-bitcoin/commit/94fcfd5853812a650d28f430107788a58e676285

**Comment by mtayyab50** [comment]
if i provide you with my admin details can you help me out please
