### ISSUE TITLE
BitCoin Payment Method for OpenCart

### ISSUE THREAD

**Issue by mtayyab50** [shaman/opencart-bitcoin#4]
I am trying to Install this module of yours but its not taking me to Checkout i.e final payment option can you tell me if there is something wrong with it as I really need this module thanks

**Comment by shaman** [comment]
please, provide your configuration example with errors logs

**Comment by mtayyab50** [comment]
it gives no error and doesn't do anything.

**Comment by mtayyab50** [comment]
if i provide you with my admin details can you help me out please

**Comment by shaman** [comment]
What is your wallet type? 
If you connect via blockchain.info API, do not forget to enable API access in your account.

**Comment by mtayyab50** [comment]
bit plastic. Do you want me to use block chain??

**Comment by shaman** [comment]
sure
this extension tested with bitcoind and blockchain.info only.

**Comment by mtayyab50** [comment]
okaye thanks just created blockchain now I will try it

**Comment by mtayyab50** [comment]
I tried still nothing when I press confirm order it does not do anything :/

**Comment by shaman** [comment]
Ok, what is your OpenCart version? Make sure that you use compatible version:

2.1 https://github.com/shaman/opencart-bitcoin
2.0 https://github.com/shaman/opencart-bitcoin/tree/opencart-2.0

Also you may send your admin panel/FTP access to opencart.ukraine@gmail.com

**Comment by mtayyab50** [comment]
please check email its sent to you and thanks i.e admin/FTP access when
done please let me know. thanks :)

On Sun, Dec 20, 2015 at 12:22 PM, Eugene Lifescale <notifications@github.com
